#!groovy

// Generated by IBM TransformationAdvisor
// Wed Feb 06 20:48:28 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}